FROM golang:1.13.5-alpine3.10 AS build
WORKDIR /go/src/github.com/yolocs/knative-policy
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o proxy-init ./cmd/proxy-init

FROM alpine:3.10 AS release
RUN apk add --no-cache ip6tables
WORKDIR /root/
COPY --from=build /go/src/github.com/yolocs/knative-policy/proxy-init .
CMD ["./proxy-init"]