apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl-proxy
  annotations:
    proxy.knative.dev/inject: "true"
    proxy.knative.dev/settings: "{\"audiences\":[\"default-broker.{{.NAMESPACE}}.svc.cluster.local\"],\"policy\":\"default-policy\",\"servicePort\":8080,\"disableInboubnd\":true}"
  name: curl-proxy
spec:
  serviceAccountName: curler
  # serviceAccountName: user-no-perm
  containers:
    # This could be any image that we can SSH into and has curl.
  - image: governmentpaas/curl-ssl
    imagePullPolicy: IfNotPresent
    name: curl-proxy
    command: ["/bin/sleep", "3650d"]
