apiVersion: v1
kind: Service
metadata:
  labels:
    app: event-echo
  name: event-echo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: event-echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-echo
  template:
    metadata:
      annotations:
        proxy.knative.dev/inject: "true"
        proxy.knative.dev/settings: "{\"policy\":\"default-policy\",\"servicePort\":8080,\"payloadPolicy\":true}"
      labels:
        app: event-echo
    spec:
      containers:
      - name: event-echo
        image: gcr.io/cshou-playground/echo-event-4fc66621723d297b4db8701699a668e6@sha256:2f11a9bcd5290299eb1f9e60554df2b2a93aa69d60822a935c1b687c2bc01442
        ports:
          - containerPort: 8080
            name: http